import "./globals.css";
import { Inter } from "next/font/google";
import { ReactNode, Suspense } from "react";
import { ApolloWrapper } from "@/lib/apollo-provider";
import Navbar from "@/components/navbar/Navbar";
import { ContentWrapper } from "@/components/ContentWrapper";

const inter = Inter({ subsets: ["latin"] });

// ???
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <ContentWrapper>
            <Suspense fallback={"no navbar xd"}>
              <Navbar />
            </Suspense>
            {children}
          </ContentWrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
}
